### PR TITLE
Support Pydantic v1 and v2

### PR DESCRIPTION
**Pull request by mattwthompson**
Stopgap bridge prior to #745, see https://docs.pydantic.dev/2.0/migration/#continue-using-pydantic-v1-features

### CODE REVIEW

**Comment by mattwthompson** [comment]
It looks like this sort of change would need to be propagated through the entire stack all at once

**Comment by daico007** [comment]
There was some additional change introduced in pydantic v1.10.12 that failed our set up, I haven't checked, but those changes probably also causing the failing tests here.

**Comment by mattwthompson** [comment]
It originally launched with a broken build (https://github.com/conda-forge/admin-requests/pull/770 begins the paper trail) but was fixed. There could be other issues, but the one I ran into is not what I'm seeing in these logs

**Comment by CalCraven** [comment]
Yeah the issue is just forcefield-utilities. I think we can quickly release get Pydantic 2 as a PR there and release it so these tests pass. 
Looks like pydantic is in gmso_xml.py and foyer_xml.py only, so that can be done.

**Comment by mattwthompson** [comment]
I've done the absolute minimum work to get that going: https://github.com/mosdef-hub/forcefield-utilities/pull/36

**Review by CalCraven — APPROVED** [review]
Probably good as a stopgap here.

**Comment by CalCraven** [comment]
@daico007 merged the PR into ffutils, so we can rerun the tests here and see if the bleeding edge tests pass.

**Comment by mattwthompson** [comment]
Ah, nice, I forgot you all set up those tests. Should be useful!

**Comment by mattwthompson** [comment]
Cool, looks like that run passed: https://github.com/mosdef-hub/gmso/actions/runs/5729710869/job/15560739904

**Review by daico007 — APPROVED** [review]
LGTM! Thanks for the fix Matt! I will probably release a patch for forcefield-utilities tomorrow, follow with a patch for GMSO to have this new fix in.

**Comment by mattwthompson** [comment]
Happy to help - could you take on the responsibility of merging this when appropriate?

No rush on a release but will be happy to see it out

**Comment by daico007** [comment]
Yes, for sure, I am planning to have this merged right before releasing (just so the tests on the main CI doesn't appear half-failed), but I could merge this now if you need this for other work.

**Comment by mattwthompson** [comment]
Not urgent at all, this won't cause us major problems for a few months

**Pull request merged**
