### PR TITLE
Remove topology_site fixture from base_test

### PR DESCRIPTION
**Pull request by rmatsum836**
Resolving #354 by removing the `topology_site` fixture and replacing with `typed_ar_system` in the LAMMPS and OpenMM tests.  Going to work on adding a `n_sites` argument as well.

### CODE REVIEW

**Comment by rsdefever** [comment]
Can we get that `n_sites` argument added before merging? We can then update the relevant tests and have it done at once.

**Comment by rmatsum836** [comment]
> Can we get that `n_sites` argument added before merging? We can then update the relevant tests and have it done at once.

I looked into this a little bit last week.  I was following this blog post: https://alysivji.github.io/pytest-fixures-with-function-arguments.html.  I was running into an issue where the pytest fixture ended up being a function, rather than a GMSO topology.  I could have been doing something wrong though and will look through this again today.

**Comment by rsdefever** [comment]
@rmatsum836 if this is too much trouble or there is urgency to getting this PR merged don't let it hold you up. I just thought it was a neat idea and fit nicely with this PR.

**Comment by rmatsum836** [comment]
So tests are going to fail, but my last commit adds an `n_sites` to `ar_system`.  This seems clunky to me since `ar_system` ends up being passed as a function instead of a topology.  The tests in `test_top.py` have been updated to reflect these changes.  Could y'all take a look and see what you think?

**Comment by umesh-timalsina** [comment]
> This seems clunky to me since ar_system ends up being passed as a function instead of a topology. The tests in test_top.py have been updated to reflect these changes.

You could add two fixtures. `typed_ar_system` would still be a topology, that uses `n_typed_ar_system`  fixture which would would be a function. If needed, could be used by other test cases.

```py
@pytest.fixture
def n_typed_ar_system(self):
    def _topology(n_sites=10):
           ..........
             return typed_ar
    return _topology

@pytest.fixture()
def typed_ar_system(self, n_typed_ar_system):
      return n_typed_ar_system(default_value)

```

**Comment by rmatsum836** [comment]
Thanks @umesh-timalsina for that suggestion.  I added two pytest fixtures: `n_ar_system` and `n_typed_ar_system`.  These two fixtures return a function and both contain the argument `n_sites` so that a user can specify how many sites to include in the topology.  

The current tests `ar_system` and `typed_ar_system` have been refactored so that `n_ar_system` and `n_typed_ar_system` respectively are called.

@rsdefever I also removed your `single` pytest fixtures and replaced them with `n_typed_`. 

Please let me know your comments and suggestions.

**Pull request merged**
