### PR TITLE
Read the docs build for gmso (Closes #319)

### LINKED ISSUE #319: Move Documentation to Read the Docs
Change Manual build (hosted in a private server) to read the docs.

### PR DESCRIPTION
**Pull request by umesh-timalsina**
Available at: https://gmso.mosdef.org/en/319-rtd-build/

### CODE REVIEW

**Comment by vyasr** [comment]
If you add this repo on RTD, it will fail to build since the master branch doesn't have a readthedocs.yaml file, but I think once it's listed on RTD you should be able to ask it to build this specific branch without having the PR merged.

**Comment by umesh-timalsina** [comment]
https://mosdef.gmso.org is already public and active. The build is not correct because `autodoc` fails to import modules.

**Comment by bdice** [comment]
@umesh-timalsina I think this issue with locating the module _could_ be related to #329, since the packages weren't defined correctly.

**Comment by umesh-timalsina** [comment]
@bdice The build is not correct because requirements are not defined for read the docs build autodoc import (we need boltons, lxml, unyt, pytest).

**Pull request merged**
