### PR TITLE
NetworkX BondGraph Connectivity (#140 Duplicate)

### PR DESCRIPTION
**Pull request by uppittu11**
Same as #140. Most of @ahy3nz code still works. Might need a few updates.

### CODE REVIEW

**Comment by umesh-timalsina** [comment]
I have refactored `connectivity.py` to consolidate some common code. Also, I think `connectivity.py` should be moved to `utils` module.

**Comment by ahy3nz** [comment]
I'm somewhat confident in Networkx's ability to identify these bonding patterns, but functions people probably need to look at: trimming any "redundant" bonded tuples and formatting the atom order of the bonded tuples (for example the improper is formatted with central atom first)

**Comment by rsdefever** [comment]
Is there a reason the ethane test doesn't check the number of dihedrals? Even the methane test could confirm that the number of dihedrals is 0.

**Comment by uppittu11** [comment]
Ok one issue I found, which is related to @ahy3nz's comment, is that if `top.enumerate_connectivity()` is run twice, duplicate connections are added. One fix would be to loop through the connections to make sure that the `connection_members` list don't match the `connection_members` list for any of the connections identified by `enumerate_connectivity()`. However, this would be super slow for a large system. 

Does anyone know a better way to prevent duplicate connections from being added?

**Comment by uppittu11** [comment]
I'm an idiot and I messed up rebasing this PR like 4 times 😬. But at least now we have a clean commit log in the "Commits" tab, and there are no more additions/deletions to `topology/core...` instead of `gmso/core...`

**Review by umesh-timalsina — APPROVED** [review]
Merged with master and tested locally, everything's working.

**Pull request merged**
