### PR TITLE
Provide ImproperType tag and name for TagGroups in XML (Closes #443)

### LINKED ISSUE #443: Add ImproperType tag and provide names for group tags in GMSO XML schema
Originally suggested by @daico007 in group meeting.

### PR DESCRIPTION
**Pull request by umesh-timalsina**
This commit adds an `ImproperType` tag to the GMSO forcefield
schema which can then be added to `DihedralTypes` group. This
will also add an attribute name of type string which can then
be added to grouped tags like `<DihedralTypes/>`, ` <AngleTypes/>`
etc...

For example
```xml
....
<DihedralTypes name='RBTorsionTypes'>
	....
	....
	<ImproperType ...
		      ...
	</ImproperType>
</DihedralTypes>
```

### CODE REVIEW

**Comment by umesh-timalsina** [comment]
This PR is ready for review. Should be merged after #442.

**Review by daico007 — APPROVED** [review]
LGTM

**Pull request merged**
