### PR TITLE
Add mol2 to formarts __init__.py

### PR DESCRIPTION
**Pull request by daico007**
Add mol2 loader import to format's `__init__.py`. Missing the line doesn't cause any issue with GMSO tests, but it failed when I tried to use it for a different PR in mbuild (https://github.com/mosdef-hub/mbuild/pull/971)

### CODE REVIEW

**Comment by justinGilmer** [comment]
Are there any other formats that we have not included here yet? If so, lets add them, and then this LGTM.

**Comment by daico007** [comment]
Based on the files in the `formats`, it seems like the `__init__.py` already get everything but the `networkx` and `mcf` conversion. But I don't think those work readily with the new registries, so might need to be handled in a different PR?

**Comment by justinGilmer** [comment]
MCF is supported with the new registry format, so that can be added. But its only for writing MCF

**Comment by daico007** [comment]
I can add that one in then

**Review by justinGilmer — APPROVED** [review]

**Pull request merged**
